apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81 
  type: LoadBalancer 