apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-autoscale
  namespace: final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 20