apiVersion: v1
kind: Secret
metadata:
  name: aws-secret  # Name of the secret
  namespace: final-project  # Ensure it matches the namespace of your deployments
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64_encoded_aws_access_key_id>
  AWS_SECRET_ACCESS_KEY: <base64_encoded_aws_secret_access_key>
  AWS_SESSION_TOKEN: <base64_encoded_aws_session_token>
  DB_USERNAME: cm9vdA== 
  DB_PASSWORD: cGFzc3dvcmQ=  